// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mcu_message.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_mcu_5fmessage_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_mcu_5fmessage_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_mcu_5fmessage_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_mcu_5fmessage_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_mcu_5fmessage_2eproto;
namespace tbox {
namespace mcu {
namespace v1 {
class McuMessage;
class McuMessageDefaultTypeInternal;
extern McuMessageDefaultTypeInternal _McuMessage_default_instance_;
}  // namespace v1
}  // namespace mcu
}  // namespace tbox
PROTOBUF_NAMESPACE_OPEN
template<> ::tbox::mcu::v1::McuMessage* Arena::CreateMaybeMessage<::tbox::mcu::v1::McuMessage>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace tbox {
namespace mcu {
namespace v1 {

// ===================================================================

class McuMessage PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:tbox.mcu.v1.McuMessage) */ {
 public:
  inline McuMessage() : McuMessage(nullptr) {};
  virtual ~McuMessage();

  McuMessage(const McuMessage& from);
  McuMessage(McuMessage&& from) noexcept
    : McuMessage() {
    *this = ::std::move(from);
  }

  inline McuMessage& operator=(const McuMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline McuMessage& operator=(McuMessage&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const McuMessage& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const McuMessage* internal_default_instance() {
    return reinterpret_cast<const McuMessage*>(
               &_McuMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(McuMessage& a, McuMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(McuMessage* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(McuMessage* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline McuMessage* New() const final {
    return CreateMaybeMessage<McuMessage>(nullptr);
  }

  McuMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<McuMessage>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const McuMessage& from);
  void MergeFrom(const McuMessage& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(McuMessage* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "tbox.mcu.v1.McuMessage";
  }
  protected:
  explicit McuMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_mcu_5fmessage_2eproto);
    return ::descriptor_table_mcu_5fmessage_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMessageDataFieldNumber = 2,
    kMessageTypeFieldNumber = 1,
  };
  // bytes message_data = 2;
  void clear_message_data();
  const std::string& message_data() const;
  void set_message_data(const std::string& value);
  void set_message_data(std::string&& value);
  void set_message_data(const char* value);
  void set_message_data(const void* value, size_t size);
  std::string* mutable_message_data();
  std::string* release_message_data();
  void set_allocated_message_data(std::string* message_data);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_message_data();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_message_data(
      std::string* message_data);
  private:
  const std::string& _internal_message_data() const;
  void _internal_set_message_data(const std::string& value);
  std::string* _internal_mutable_message_data();
  public:

  // uint32 message_type = 1;
  void clear_message_type();
  ::PROTOBUF_NAMESPACE_ID::uint32 message_type() const;
  void set_message_type(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_message_type() const;
  void _internal_set_message_type(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:tbox.mcu.v1.McuMessage)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_data_;
  ::PROTOBUF_NAMESPACE_ID::uint32 message_type_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_mcu_5fmessage_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// McuMessage

// uint32 message_type = 1;
inline void McuMessage::clear_message_type() {
  message_type_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 McuMessage::_internal_message_type() const {
  return message_type_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 McuMessage::message_type() const {
  // @@protoc_insertion_point(field_get:tbox.mcu.v1.McuMessage.message_type)
  return _internal_message_type();
}
inline void McuMessage::_internal_set_message_type(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  message_type_ = value;
}
inline void McuMessage::set_message_type(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_message_type(value);
  // @@protoc_insertion_point(field_set:tbox.mcu.v1.McuMessage.message_type)
}

// bytes message_data = 2;
inline void McuMessage::clear_message_data() {
  message_data_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& McuMessage::message_data() const {
  // @@protoc_insertion_point(field_get:tbox.mcu.v1.McuMessage.message_data)
  return _internal_message_data();
}
inline void McuMessage::set_message_data(const std::string& value) {
  _internal_set_message_data(value);
  // @@protoc_insertion_point(field_set:tbox.mcu.v1.McuMessage.message_data)
}
inline std::string* McuMessage::mutable_message_data() {
  // @@protoc_insertion_point(field_mutable:tbox.mcu.v1.McuMessage.message_data)
  return _internal_mutable_message_data();
}
inline const std::string& McuMessage::_internal_message_data() const {
  return message_data_.Get();
}
inline void McuMessage::_internal_set_message_data(const std::string& value) {
  
  message_data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void McuMessage::set_message_data(std::string&& value) {
  
  message_data_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:tbox.mcu.v1.McuMessage.message_data)
}
inline void McuMessage::set_message_data(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  message_data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:tbox.mcu.v1.McuMessage.message_data)
}
inline void McuMessage::set_message_data(const void* value,
    size_t size) {
  
  message_data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:tbox.mcu.v1.McuMessage.message_data)
}
inline std::string* McuMessage::_internal_mutable_message_data() {
  
  return message_data_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* McuMessage::release_message_data() {
  // @@protoc_insertion_point(field_release:tbox.mcu.v1.McuMessage.message_data)
  return message_data_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void McuMessage::set_allocated_message_data(std::string* message_data) {
  if (message_data != nullptr) {
    
  } else {
    
  }
  message_data_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), message_data,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:tbox.mcu.v1.McuMessage.message_data)
}
inline std::string* McuMessage::unsafe_arena_release_message_data() {
  // @@protoc_insertion_point(field_unsafe_arena_release:tbox.mcu.v1.McuMessage.message_data)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return message_data_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void McuMessage::unsafe_arena_set_allocated_message_data(
    std::string* message_data) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (message_data != nullptr) {
    
  } else {
    
  }
  message_data_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      message_data, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:tbox.mcu.v1.McuMessage.message_data)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace v1
}  // namespace mcu
}  // namespace tbox

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_mcu_5fmessage_2eproto
